Repositioning the jquery <script> tag
When i tried to run the template view example, the console.log gave me the next error:
"Uncaught TypeError: Property '$' of object #<Object> is not a function"

This happened because you had the jquery scrip tag on a wrong position, just below of backbone.min.js script tag.
Now i have changing the position, juts above of underscore-min.js script tag